[package]
name = "Day-08-treetop-tree-house"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utility-2022 = { path = "../utility-2022" }
